site_name: FPGC6 Documentation

theme:
    name: material
    custom_dir: overrides

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - codehilite
  - admonition

repo_name: b4rt-dev/FPGC6
repo_url: https://github.com/b4rt-dev/fpgc6

site_url: https://www.b4rt.nl/fpgc

edit_uri: edit/master/Documentation/docs/

use_directory_urls: False

nav:
  - Introduction: 'index.md'
  - 'arch.md'
  - 'cpu.md'
  - 'doc.md'
  - 'gpu.md'
  - 'map.md'
  - 'quartus.md'
  - 'todos.md'